### ISSUE TITLE
Add hashing function

### ISSUE THREAD

**Issue by peter279k** [selective-php/util#6]
This issue is about the feature request.

PHP has some hashing approaches are available.

Such as `md5`, sha` and so on.

I think we can integrate all hashing approaches for some helpers.

The hashing algorithms are as follows:

- `SHA`
- `MD5`
- `Bcrypt`
- `CRYPT_BLOWFISH `
- `ARGON2I `
- `ARGON2ID `

If I miss the hashing algorithms, please write comments to let me know.

@odan, what do you think about this?

**Comment by odan** [comment]
PHP already has a very and good `hash` function. 

https://www.php.net/manual/en/function.hash.php

I think it would be redundant to add more functions without any benefits.

**Comment by peter279k** [comment]
Ok. It looks like the native `hash` function is good enough.

Closed.
