### ISSUE TITLE
Add related .htpasswd functions

### ISSUE THREAD

**Issue by peter279k** [selective-php/util#7]
In the past of week, I've researched about the `.htpasswd` on `Apache` server.

It provides some password encryption for creating a `.htpasswd` file to do HTTP basic authentication.

Here is the detailed [reference](https://httpd.apache.org/docs/2.4/misc/password_encryptions.html).

I want to create related function to integrate a valid password to make `.htpasswd` file dynamically.

I think we can create one function named `http_basic_auth` (or other names) to dispatch the available hashing approach and generate the hashed result.

**Comment by odan** [comment]
A quick [search](https://packagist.org/packages/stevenbuehner/htpasswd-manager?query=htpasswd&type=library) on packagist showed me that there are good libraries like [rafaelgou/php-apache2-basic-auth](https://packagist.org/packages/rafaelgou/php-apache2-basic-auth).

The scope of the suggested functionality is also very large. This feature is too big for such a small collection of general helper functions. We should not make this "util" package bigger, but smaller. Maybe the name "util" was wrong. We should extract the existing functions into smaller, more specialized libaries instead. I don't want to blow this lib up and mix everything together :-)

**Comment by peter279k** [comment]
You are right.

I think we can rename to helpers.

What do you think?
